SELECT b.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
        JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE bs.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD') AND bs.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY b.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY b.AUTHOR_ID ASC, CATEGORY DESC;