-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT REST_ID,FOOD_TYPE, REST_NAME, FAVORITES, ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rk
    FROM REST_INFO
)
WHERE rk = 1
ORDER BY FOOD_TYPE DESC
;