-- 코드를 입력하세요
-- WITH pre AS(
--     SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
--     FROM ANIMAL_INS 
--     WHERE SEX_UPON_INTAKE LIKE 'Intact%'
-- ),
-- post AS(
--     SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_OUTCOME
--     FROM ANIMAL_OUTS  
-- )
-- SELECT p.ANIMAL_ID, p.ANIMAL_TYPE, p.NAME
-- FROM pre p join post po ON p.ANIMAL_ID = po.ANIMAL_ID
-- WHERE p.SEX_UPON_INTAKE != po.SEX_UPON_OUTCOME
-- ORDER BY p.ANIMAL_ID;

SELECT
    ins.ANIMAL_ID,
    ins.ANIMAL_TYPE,
    ins.NAME
FROM
    ANIMAL_INS ins
JOIN
    ANIMAL_OUTS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE
    ins.SEX_UPON_INTAKE LIKE 'Intact%' 
    AND outs.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY
    ins.ANIMAL_ID;