SELECT EXTRACT(YEAR FROM SALES_DATE)  AS YEAR,
       EXTRACT(MONTH FROM SALES_DATE) AS MONTH, 
       GENDER, 
       COUNT(DISTINCT i.USER_ID) AS USERS
FROM USER_INFO i JOIN ONLINE_SALE s ON i.user_id = s.user_id
WHERE GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALES_DATE) ,
         EXTRACT(MONTH FROM SALES_DATE) , 
         GENDER
ORDER BY YEAR, MONTH, GENDER;