-- 코드를 입력하세요
SELECT t.NAME, t.DATETIME
FROM (
    SELECT i.NAME, i.DATETIME, ROW_NUMBER() OVER(ORDER BY i.DATETIME ASC) rnk
    FROM ANIMAL_INS i LEFT JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
    WHERE o.DATETIME IS NULL
    )t
WHERE rnk <= 3;