SELECT ap.APNT_NO, p.PT_NAME, p.PT_NO, ap.MCDP_CD, d.DR_NAME, ap.APNT_YMD
FROM PATIENT p JOIN APPOINTMENT ap ON  p.PT_NO = ap.PT_NO 
        JOIN DOCTOR d ON ap.MDDR_ID = d.DR_ID
WHERE ap.APNT_YMD >= TO_DATE('2022-04-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
  AND ap.APNT_YMD <  TO_DATE('2022-04-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND ap.MCDP_CD = 'CS' AND APNT_CNCL_YN='N'
ORDER BY APNT_YMD ASC;