WITH ReviewRank AS (
    SELECT MEMBER_ID,
            RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) as rnk 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT p.MEMBER_NAME,
       r.REVIEW_TEXT,
       TO_CHAR(r.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE 
FROM MEMBER_PROFILE p
    JOIN REST_REVIEW r ON p.MEMBER_ID = r.MEMBER_ID
WHERE p.MEMBER_ID IN (SELECT MEMBER_ID FROM ReviewRank WHERE rnk = 1) 
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;