SELECT MONTH, CAR_ID , COUNT(*) AS RECORDS
FROM (SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID 
            , COUNT(*) OVER (PARTITION BY CAR_ID)AS TOTAL_RECORDS
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE START_DATE >= TO_DATE('20220801','YYYYMMDD') AND START_DATE <= TO_DATE('20221031','YYYYMMDD')
     )
WHERE TOTAL_RECORDS >= 5
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;