-- 코드를 입력하세요
SELECT DISTINCT(c.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR c JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
        ON c.CAR_ID = rh.CAR_ID
WHERE c.CAR_TYPE = '세단' AND rh.START_DATE>=TO_DATE('20221001', 'YYYYMMDD')
ORDER BY c.CAR_ID DESC;